const en = {
  header: {
    logo: "Kaelis AI",
    nav: {
      tarotSpreads: "Tarot Spreads",
      ourApp: "Our App",
      termsOfUse: "Terms of Use",
    },
    downloadApp: "Download App",
    language: "EN",
    languageNames: {
      en: "En",
      ru: "Rus",
      uk: "Ua",
    },
  },
  hero: {
    titleLine1: "Your AI Guide",
    titleToThe: "to the",
    titleHighlight: "Esoteric",
    titleWorld: "World",
    description: "AI-powered tarot readings crafted for clarity,\nguidance, and self-discovery.",
    cta: "Pick a Card to Start Your Reading",
    ctaHover: "Get Your Readings",
  },
  cards: {
    love: "Love",
    yesNo: "Yes/No",
    oneCard: "One Card",
    threeCards: "Three Cards",
    work: "Work",
    family: "Family",
    money: "Money",
  },
  topBlock: {
    eyebrow: "AI Powered",
    titleLine1: "Discover Yourself,",
    titleLine2: "One Insight at a Time",
    description:
      "Understand your thoughts, emotions, and patterns with AI-guided reflections, personalized readings, and mindful tools designed for self-discovery",
  },
  categoryPage: {
    categoryLabel: "Category",
    returnToMain: "Return to Main",
    returnToPrefix: "Return to",
    getYourReadings: "Get Your Readings",
    topBlock: {
      changeQuestion: "Change Question",
      categoryPrefix: "Category:",
      askTitle: "Ask a Question",
      askDescription: "The cards hold the answers you seek. Let the wisdom of Tarot guide your path",
      placeholder: "Describe your question…",
      continue: "Continue",
      chooseTitle: "Choose {count} {cards}",
      cardWordOne: "Card",
      cardWordFew: "Cards",
      cardWordMany: "Cards",
      chooseDescription: "“This is a question that i have for this tarot reader. So i will ask it here”",
      findTitle: "Find answers",
      tapToReveal: "Tap on the Card to Reveal it",
      answerQuestion: "Answer the Question",
      truthTitle: "The Truth",
      truthDescription: "“This is a question that i have for this tarot reader. So i will ask it here”",
      startOver: "Start Over",
      moreInfo: "More Info",
      cardDescription:
        "The Knight of Wands is a tarot card that stands for high energy, bold action, passion, and sudden adventure. It shows that you are ready to chase a goal or dream with speed and power. When you see this card, it means go fast, take risks, and act with a brave heart.",
      analyst: "Analyst",
      guides: {
        analyst: "Analyst",
        witch: "Witch",
        psychologist: "Psychologist",
        friend: "Friend",
      },
      guideDescriptions: {
        analyst: "Data-driven, precise logical breakdowns",
        witch: "Subconscious archetypes & syncs",
        psychologist: "Cognitive behavioral & mindset models",
        friend: "Sincere, warm empathetic feedback",
      },
    },
  },
  footer: {
    logo: "Kaelis AI",
    links: {
      childrensPrivacyPolicy: "Children’s Privacy Policy",
      refundSubscriptionPolicy: "Refund & Subscription Policy",
      privacyPolicy: "Private Policy",
    },
  },
  termsOfUse: {
    eyebrow: "Legal Agreement",
    title: "Terms of Use",
    lastUpdated: "Last updated: August 13, 2026",
    headerMarker: "Kaela AI Terms of Service",
    sections: [
      {
        title: "Introduction",
        body: "Welcome to Kaela AI. These Terms of Use govern your access to and use of our mystical AI-driven tarot reading platforms, mobile applications, and web services. By invoking our virtual cards and digital spreads, you step into a pact of mutual understanding and respect with Kaela AI.",
      },
      {
        title: "Acceptance of Terms",
        body: "By accessing, browsing, or utilizing the readings provided by Kaela AI, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use. If you do not agree to these terms, we ask that you withdraw from our digital sanctuary.",
      },
      {
        title: "Description of Service",
        body: "Kaela AI provides digital entertainment services incorporating artificial intelligence models trained to interpret tarot cards, astrological elements, and psychic symbology. The interpretations, answers, and advice generated by our AI system are curated for mystical exploration, personal contemplation, and general guidance.",
        note: {
          label: "Please Note:",
          text: " Our AI readings are not substitutes for professional medical, legal, financial, or psychological counseling. The paths of the future are ever-shifting, and you hold ultimate sovereign agency over your choices.",
        },
      },
      {
        title: "User Accounts",
        body: "To experience the full breadth of the cosmic spreads, you may be invited to establish a personal account. You are responsible for safeguarding your account details, passwords, and any mystical queries submitted through our portal. Any action registered under your account remains your primary spiritual and legal responsibility.",
      },
      {
        title: "Intellectual Property",
        body: "The beautiful design of our cards, original illustrations, cosmic graphics, proprietary AI tarot models, and custom interfaces are the intellectual property of Kaela AI and our creative artisans. You are granted a limited, personal, non-transferable license to read and share your private card spreads for personal, non-commercial purposes.",
      },
      {
        title: "Limitation of Liability",
        body: "Kaela AI and its human companions shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or the inability to use our services, or for any life actions taken based on our AI tarot interpretations. Your destiny is carved by your own hands.",
      },
      {
        title: "Changes to Terms",
        body: "We reserve the right to refine or alter these mystical guidelines at any time to align with new planetary transits or service upgrades. When changes occur, we will adjust the date at the summit of this document. Continued use of the platform constitutes acceptance of the new celestial terms.",
      },
      {
        title: "Contact Information",
        body: "Should you have any inquiries, cosmic queries, or require assistance deciphering our legal parameters, our guardians of support are ready to assist you. You may write to us at:",
        contact: {
          name: "Kaela AI Sanctuary HQ",
          email: "Email: cosmos@kaela.ai",
          address: "Address: 777 Ethereal Lane, Suite Nebula, San Francisco, CA",
        },
      },
    ],
  },
};

export type Dictionary = typeof en;

export default en;
